version: "3.9"
services:
    front-end:
        build: ./front-end
        image: front-end
        ports:
        - "80:80"
    back-end:
        build: ./back-end
        image: back-end
        ports:
        - "3000:3000"